<?php

namespace App\Helpers;

class EmailPattern
{
    const CREATE = 'CREATE_EMAIL_PATTERN';
    const UPDATE = 'UPDATE_EMAIL_PATTERN';
    const DELETE = 'DELETE_EMAIL_PATTERN';
    const APPROVED_BY_TL = 'TL_APPROVAL_EMAIL_PATTERN';
    const DISAPPROVED_BY_TL = 'TL_DISAPPROVAL_EMAIL_PATTERN';
    const APPROVED_BY_ADMIN = 'ADMIN_APPROVAL_EMAIL_PATTERN';
    const DISAPPROVED_BY_ADMIN = 'ADMIN_DISAPPROVAL_EMAIL_PATTERN';
}
